import { User, Office, DartaLetter, ChalaniLetter, Notification } from './types';

// Mock Document Types
export const mockDocumentTypes = [
  { id: 'doc-type-1', code: 'OL', name: 'Official Letter' },
  { id: 'doc-type-2', code: 'CORR', name: 'Correspondence' },
  { id: 'doc-type-3', code: 'MEMO', name: 'Memo/Internal Note' },
  { id: 'doc-type-4', code: 'RPT', name: 'Report' },
  { id: 'doc-type-5', code: 'INV', name: 'Invoice/Bill' },
  { id: 'doc-type-6', code: 'CONT', name: 'Contract/Agreement' },
  { id: 'doc-type-7', code: 'CIRC', name: 'Circular/Notice' },
  { id: 'doc-type-8', code: 'PROP', name: 'Proposal' },
  { id: 'doc-type-9', code: 'COMP', name: 'Complaint' },
  { id: 'doc-type-10', code: 'AUDIT', name: 'Audit Report' },
  { id: 'doc-type-11', code: 'OTHER', name: 'Other' },
];

// Mock Users
export const mockUsers: User[] = [
  {
    id: 'usr-001',
    email: 'admin@ntc.net.np',
    name: 'Ram Bahadur Thapa',
    designation: 'System Administrator',
    role: 'administrator',
    officeId: 'off-001',
    officeName: 'Head Office - IT Department',
    permissions: [
      { module: 'users', actions: ['view', 'create', 'edit', 'delete'] },
      { module: 'offices', actions: ['view', 'create', 'edit', 'delete'] },
      { module: 'darta', actions: ['view', 'create', 'edit', 'delete', 'approve'] },
      { module: 'chalani', actions: ['view', 'create', 'edit', 'delete', 'approve'] },
      { module: 'reports', actions: ['view'] },
      { module: 'audit', actions: ['view'] },
    ],
    isActive: true,
    createdAt: '2024-01-15',
  },
  {
    id: 'usr-002',
    email: 'clerk@ntc.net.np',
    name: 'Sita Sharma',
    designation: 'Office Clerk',
    role: 'clerk',
    officeId: 'off-002',
    officeName: 'Central Regional Office',
    permissions: [
      { module: 'darta', actions: ['view', 'create', 'edit'] },
      { module: 'chalani', actions: ['view', 'create', 'edit'] },
    ],
    isActive: true,
    createdAt: '2024-02-10',
  },
  {
    id: 'usr-003',
    email: 'officer@ntc.net.np',
    name: 'Hari Prasad Acharya',
    designation: 'Department Officer',
    role: 'department_officer',
    officeId: 'off-003',
    officeName: 'Finance Department',
    permissions: [
      { module: 'darta', actions: ['view', 'edit', 'approve'] },
      { module: 'chalani', actions: ['view', 'edit', 'approve'] },
      { module: 'reports', actions: ['view'] },
    ],
    isActive: true,
    createdAt: '2024-01-20',
  },
  {
    id: 'usr-004',
    email: 'director@ntc.net.np',
    name: 'Dr. Krishna Bahadur KC',
    designation: 'Executive Director',
    role: 'approving_authority',
    officeId: 'off-001',
    officeName: 'Head Office',
    permissions: [
      { module: 'darta', actions: ['view', 'approve'] },
      { module: 'chalani', actions: ['view', 'approve'] },
      { module: 'reports', actions: ['view'] },
    ],
    isActive: true,
    createdAt: '2023-06-01',
  },
  {
    id: 'usr-005',
    email: 'staff@ntc.net.np',
    name: 'Gita Kumari Rai',
    designation: 'Junior Staff',
    role: 'general_staff',
    officeId: 'off-002',
    officeName: 'Central Regional Office',
    permissions: [
      { module: 'darta', actions: ['view'] },
      { module: 'chalani', actions: ['view', 'create'] },
    ],
    isActive: true,
    createdAt: '2024-03-01',
  },
  {
    id: 'usr-006',
    email: 'auditor@ntc.net.np',
    name: 'Bishnu Prasad Poudel',
    designation: 'Internal Auditor',
    role: 'auditor',
    officeId: 'off-001',
    officeName: 'Head Office - Audit',
    permissions: [
      { module: 'darta', actions: ['view'] },
      { module: 'chalani', actions: ['view'] },
      { module: 'reports', actions: ['view'] },
      { module: 'audit', actions: ['view'] },
    ],
    isActive: true,
    createdAt: '2024-01-10',
  },
];

// Mock Offices (Org Hierarchy)
export const mockOffices: Office[] = [
  {
    id: 'off-001',
    code: 'NTC-HO',
    name: 'Nepal Telecom Head Office',
    type: 'head_office',
    location: 'Bhadrakali, Kathmandu',
    isActive: true,
  },
  {
    id: 'off-002',
    code: 'NTC-CRO',
    name: 'Central Regional Office',
    type: 'regional',
    location: 'Pulchowk, Lalitpur',
    parentId: 'off-001',
    headUserId: 'usr-003',
    isActive: true,
  },
  {
    id: 'off-003',
    code: 'NTC-FIN',
    name: 'Finance Department',
    type: 'department',
    location: 'Bhadrakali, Kathmandu',
    parentId: 'off-001',
    headUserId: 'usr-003',
    isActive: true,
  },
  {
    id: 'off-004',
    code: 'NTC-ERO',
    name: 'Eastern Regional Office',
    type: 'regional',
    location: 'Biratnagar',
    parentId: 'off-001',
    isActive: true,
  },
  {
    id: 'off-005',
    code: 'NTC-WRO',
    name: 'Western Regional Office',
    type: 'regional',
    location: 'Pokhara',
    parentId: 'off-001',
    isActive: true,
  },
  {
    id: 'off-006',
    code: 'NTC-IT',
    name: 'IT Department',
    type: 'department',
    location: 'Bhadrakali, Kathmandu',
    parentId: 'off-001',
    headUserId: 'usr-001',
    isActive: true,
  },
  {
    id: 'off-007',
    code: 'NTC-HR',
    name: 'Human Resources Department',
    type: 'department',
    location: 'Bhadrakali, Kathmandu',
    parentId: 'off-001',
    isActive: true,
  },
  {
    id: 'off-008',
    code: 'NTC-KTM-BR1',
    name: 'Kathmandu Branch - Maitighar',
    type: 'branch',
    location: 'Maitighar, Kathmandu',
    parentId: 'off-002',
    isActive: true,
  },
];

// Mock Darta Letters
export const mockDartaLetters: DartaLetter[] = [
  {
    id: 'darta-001',
    dartaNumber: '2081-001',
    fiscalYear: '2081/82',
    senderName: 'Ministry of Communication',
    senderOrg: 'Government of Nepal',
    letterDate: '2024-11-01',
    receivedDate: '2024-11-03',
    subject: 'Request for Annual Report Submission',
    priority: 'urgent',
    confidentiality: 'internal',
    documentType: 'Official Letter',
    status: 'in_review',
    currentHandler: 'usr-003',
    currentHandlerName: 'Hari Prasad Acharya',
    attachments: [
      {
        id: 'doc-001',
        name: 'Request_Letter.pdf',
        type: 'application/pdf',
        size: 245000,
        uploadedAt: '2024-11-03T10:30:00Z',
        uploadedBy: 'usr-002',
        url: '#',
      },
    ],
    createdAt: '2024-11-03T10:30:00Z',
    createdBy: 'usr-002',
  },
  {
    id: 'darta-002',
    dartaNumber: '2081-002',
    fiscalYear: '2081/82',
    senderName: 'Nepal Electricity Authority',
    senderOrg: 'NEA',
    letterDate: '2024-11-05',
    receivedDate: '2024-11-06',
    subject: 'Electricity Bill Dispute Resolution',
    priority: 'normal',
    confidentiality: 'public',
    documentType: 'Correspondence',
    status: 'pending',
    currentHandler: 'usr-002',
    currentHandlerName: 'Sita Sharma',
    attachments: [],
    createdAt: '2024-11-06T09:15:00Z',
    createdBy: 'usr-002',
  },
  {
    id: 'darta-003',
    dartaNumber: '2081-003',
    fiscalYear: '2081/82',
    senderName: 'Internal Audit Division',
    senderOrg: 'Nepal Telecom',
    letterDate: '2024-11-08',
    receivedDate: '2024-11-08',
    subject: 'Quarterly Audit Findings',
    priority: 'confidential',
    confidentiality: 'confidential',
    documentType: 'Audit Report',
    status: 'approved',
    currentHandler: 'usr-004',
    currentHandlerName: 'Dr. Krishna Bahadur KC',
    attachments: [
      {
        id: 'doc-002',
        name: 'Audit_Report_Q3.pdf',
        type: 'application/pdf',
        size: 1250000,
        uploadedAt: '2024-11-08T14:00:00Z',
        uploadedBy: 'usr-006',
        url: '#',
      },
    ],
    createdAt: '2024-11-08T14:00:00Z',
    createdBy: 'usr-006',
  },
];

// Mock Chalani Letters
export const mockChalaniLetters: ChalaniLetter[] = [
  {
    id: 'chalani-001',
    chalaniNumber: 'CH-2081-001',
    fiscalYear: '2081/82',
    receiverName: 'Ministry of Communication',
    receiverOrg: 'Government of Nepal',
    receiverType: 'external',
    subject: 'Annual Report Submission FY 2080/81',
    priority: 'normal',
    status: 'closed',
    content: '<p>Respected Sir/Madam,</p><p>Please find attached the Annual Report...</p>',
    attachments: [],
    createdAt: '2024-11-10T11:00:00Z',
    createdBy: 'usr-003',
    dispatchedAt: '2024-11-12T15:30:00Z',
  },
  {
    id: 'chalani-002',
    chalaniNumber: 'CH-2081-002',
    fiscalYear: '2081/82',
    receiverName: 'Eastern Regional Office',
    receiverOrg: 'Nepal Telecom',
    receiverType: 'internal',
    subject: 'Budget Allocation for Q4',
    priority: 'urgent',
    status: 'in_review',
    content: '<p>Dear Colleagues,</p><p>This is to inform you about the budget allocation...</p>',
    attachments: [],
    createdAt: '2024-11-11T09:30:00Z',
    createdBy: 'usr-003',
  },
];

// Mock Notifications
export const mockNotifications: Notification[] = [
  {
    id: 'notif-001',
    type: 'task',
    title: 'New Darta Assigned',
    message: 'You have been assigned to review Darta #2081-001',
    isRead: false,
    createdAt: '2024-11-13T08:00:00Z',
    linkTo: '/darta/darta-001',
  },
  {
    id: 'notif-002',
    type: 'sla_warning',
    title: 'SLA Warning',
    message: 'Darta #2081-002 is approaching deadline (2 hours remaining)',
    isRead: false,
    createdAt: '2024-11-13T10:30:00Z',
    linkTo: '/darta/darta-002',
  },
  {
    id: 'notif-003',
    type: 'info',
    title: 'Chalani Dispatched',
    message: 'Chalani #CH-2081-001 has been successfully dispatched',
    isRead: true,
    createdAt: '2024-11-12T15:35:00Z',
    linkTo: '/chalani/chalani-001',
  },
];

// Dashboard stats
export const mockDashboardStats = {
  totalDarta: 156,
  pendingDarta: 23,
  totalChalani: 89,
  pendingChalani: 12,
  overdueTasks: 5,
  completedThisWeek: 34,
};
