# Generated by Django 4.2.27 on 2026-01-20 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChalaniLetter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chalani_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('fiscal_year', models.CharField(max_length=10)),
                ('receiver_name', models.CharField(max_length=255)),
                ('receiver_org', models.CharField(blank=True, max_length=255)),
                ('receiver_address', models.TextField(blank=True)),
                ('receiver_type', models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='external', max_length=20)),
                ('subject', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('confidential', 'Confidential')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('dispatched', 'Dispatched')], default='draft', max_length=20)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sla_deadline', models.DateTimeField(blank=True, null=True)),
                ('is_sla_breached', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chalani', to=settings.AUTH_USER_MODEL)),
                ('dispatched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_chalani', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chalani Letter',
                'verbose_name_plural': 'Chalani Letters',
                'db_table': 'chalani_letters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LetterTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('name_nepali', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Letter Template',
                'verbose_name_plural': 'Letter Templates',
                'db_table': 'letter_templates',
            },
        ),
        migrations.CreateModel(
            name='ChalaniRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('is_internal', models.BooleanField(default=False)),
                ('chalani', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cc_recipients', to='chalani.chalaniletter')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.office')),
            ],
            options={
                'db_table': 'chalani_recipients',
            },
        ),
    ]
