# Generated by Django 4.2.27 on 2026-01-20 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chalani', '0001_initial'),
        ('darta', '0001_initial'),
        ('workflow', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chalaniletter',
            name='file_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chalani_letters', to='workflow.filetracker'),
        ),
        migrations.AddField(
            model_name='chalaniletter',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chalani_letters', to='organization.office'),
        ),
        migrations.AddField(
            model_name='chalaniletter',
            name='receiver_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_chalani', to='organization.office'),
        ),
        migrations.AddField(
            model_name='chalaniletter',
            name='reference_darta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response_chalani', to='darta.dartaletter'),
        ),
        migrations.AddField(
            model_name='chalaniletter',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chalani.lettertemplate'),
        ),
    ]
