# Generated by Django 4.2.27 on 2026-01-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_add_office_head'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='office',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Office', 'verbose_name_plural': 'Offices'},
        ),
        migrations.AddField(
            model_name='office',
            name='depth',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='office',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='office',
            name='order',
            field=models.IntegerField(default=0, help_text='Sort order within the same parent office'),
        ),
        migrations.AddField(
            model_name='office',
            name='path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='office',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='office',
            name='type',
            field=models.CharField(choices=[('head_office', 'Head Office'), ('regional', 'Regional Office'), ('branch', 'Branch Office'), ('department', 'Department'), ('section', 'Section'), ('unit', 'Unit')], max_length=20),
        ),
    ]
