# Generated by Django 4.2.27 on 2026-01-20 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DartaLetter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('darta_number', models.CharField(max_length=50, unique=True)),
                ('fiscal_year', models.CharField(max_length=10)),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_org', models.CharField(blank=True, max_length=255)),
                ('sender_address', models.TextField(blank=True)),
                ('letter_date', models.DateField()),
                ('received_date', models.DateField()),
                ('subject', models.CharField(max_length=500)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('confidential', 'Confidential')], default='normal', max_length=20)),
                ('confidentiality', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('secret', 'Secret')], default='public', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed'), ('terminated', 'Terminated')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sla_deadline', models.DateTimeField(blank=True, null=True)),
                ('is_sla_breached', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_darta', to=settings.AUTH_USER_MODEL)),
                ('current_handler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handling_darta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Darta Letter',
                'verbose_name_plural': 'Darta Letters',
                'db_table': 'darta_letters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('name_nepali', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Document Type',
                'verbose_name_plural': 'Document Types',
                'db_table': 'document_types',
            },
        ),
        migrations.CreateModel(
            name='DartaRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_type', models.CharField(choices=[('primary', 'Primary'), ('cc', 'CC (Bodhartha)')], default='primary', max_length=20)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('darta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='darta.dartaletter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_darta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'darta_recipients',
            },
        ),
        migrations.AddField(
            model_name='dartaletter',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='darta.documenttype'),
        ),
    ]
