# Generated by Django 4.2.27 on 2026-01-20 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('darta', '0001_initial'),
        ('organization', '0001_initial'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dartaletter',
            name='file_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='darta_letters', to='workflow.filetracker'),
        ),
        migrations.AddField(
            model_name='dartaletter',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='darta_letters', to='organization.office'),
        ),
        migrations.AlterUniqueTogether(
            name='dartarecipient',
            unique_together={('darta', 'user')},
        ),
    ]
